apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub2
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.pubsub2.redis.host }}
  - name: redisPassword
    value: {{ .Values.pubsub2.redis.password }}
  - name: poolSize
    value: {{ .Values.pubsub2.redis.poolSize }}
  - name: concurrency
    value: {{ .Values.pubsub2.redis.concurrency }}