apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: store-lock
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.stateStore.lock.redis.host }}
  - name: keyPrefix
    value: {{ .Values.stateStore.lock.redis.keyPrefix }}
  - name: poolSize
    value: {{ .Values.stateStore.lock.redis.poolSize }}
  - name: redisDB
    value: {{ .Values.stateStore.lock.redis.db }}

---

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: store-business
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.stateStore.business.redis.host }}
  - name: redisDB
    value: {{ .Values.stateStore.business.redis.db }}
  - name: keyPrefix
    value: {{ .Values.stateStore.business.redis.keyPrefix }}
